[default.extend-words]
gir = "gir"
inout = "inout"
numer = "numer" # Short for numerator in GStreamer
ue = "ue" # End of word after mnemonic
reate = "reate" # End of word after mnemonic
hread = "hread" # End of word after mnemonic
Commet = "Commet" # Matrix client name

[type.po]
extend-glob = ["*.po"]
check-file = false

[type.json]
extend-glob = ["*.json"]
check-file = false

[type.png]
extend-glob = ["*.png"]
check-file = false
